services:
  backend:
    build: 
      context: ./backend
    container_name: backend_service
    networks:
      - docker_network
    restart: on-failure

  nginx:
    image: nginx:1.29
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - docker_network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80/"]
      interval: 60s
      retries: 3
      timeout: 10s
      start_period: 10s
    restart: on-failure

networks:
  docker_network:
    driver: bridge